### ISSUE TITLE
Mac Version: Cannot Display COA Tools in GIMP File Menu for Mac…

### ISSUE THREAD

**Issue by artisan21** [ndee85/coa_tools#111]
Hello,

This is my first time with an issue on GitHub. I have installed the Python plug-in script for COA Tools in the /Users/MYNAME/GIMP/2.8 folder (I had it in the plugins folder, but realize that this was the wrong location to place it). It will not show up in the File Menu for GIMP for Mac. Do I have to do something to make it executable, or is it something else? Can you help me with this please? 

I own a late 2009 iMac, running MacOS High Sierra 10.13.6. I have three versions of GIMP, which are versions 2.8.22, 2.10.6, and McGIMP 2.10.4, which are all for the Mac. Do you think that this could be the issue as well? Also, if I have to make it executable, what Terminal command should I use?

Forgive me for asking such a novice question, but using the Terminal in Mac is not easy for me.

Thank you for your help. It is duly appreciated.

**Comment by alcalyn** [comment]
Hi, I am on Ubuntu 18, not mac.

### Plugin folder

To install the GIMP plugin, I downloaded this repo, and moved the file `coatools_exporter.py` into `/home/me/.gimp-2.8/plug-ins`, so I have:

`/home/me/.gimp-2.8/plug-ins/coatools_exporter.py`

### Make sure it is executable

Also, it has execution rights. You can add it with the command:

``` bash
$ cd ~/.gimp-2.8/plug-ins
$ sudo chmod sudo chmod +x coatools_exporter.py
$ ls -l
total 8
-rwxr-xr-x 1 me me 8156 janv.  5 21:14 coatools_exporter.py
```

And when I reloaded Gimp, it worked, I have "Export to COA tools" in the "File" menu.

### Check if you're running the good gimp bin

You can make sure you have moved the script in the good version of Gimp, and running the good Gimp. Maybe your Gimp icon is another instance. To remove any doubt about it, use Gimp from terminal:

``` bash
# Check gimp version
$ gimp --version
GIMP version 2.8.22

# Check if plugin is installed with execute rights
$ ls -l ~/.gimp-2.8/plug-ins
total 8
-rwxr-xr-x 1 me me 8156 janv.  5 21:14 coatools_exporter.py

# Run this Gimp
$ gimp
```

**Comment by ndee85** [comment]
@alcalyn 
Thanks for helping out. The GIMP exporter was not written by me, so I have no real experience with it.
Closing issue since it seems to be resolved.
