### ISSUE TITLE
Dragonbones plugin can not export

### ISSUE THREAD

**Issue by zhjawe** [ndee85/coa_tools#118]
I click "Export Dragonbones " button,console shows "Export path does not exists.Set a valid Export path"

**Comment by alcalyn** [comment]
Solved here https://github.com/ndee85/coa_tools/issues/102

**Comment by ndee85** [comment]
Before exporting, a valid path needs to be set. Once done, everything is exported to that location.
If it does not work, please share a file to have a look into.
