### ISSUE TITLE
Z-order editing for those of us without JSON files to import

### ISSUE THREAD

**Issue by GimmickyApps** [ndee85/coa_tools#12]
Hi,
I'm wondering if this is something built in or made easier by CoaTools...I don't have Photoshop so I'm waiting on the Gimp exporter, but I may not be able to use it before my project deadline.  So, how does what you might call Z-order in a 2D context work in Blender's 3D context?  From http://www.robotsandchocolates.com/2015/04/2d-cutout-animation-in-blender-written.html I gathered that it's Y, not Z, that we might need to change, which seems to be the case.  However, if I change the Y value by holding G+Y on a sprite, it flickers crazily and does not seem to land in the right order I would like. 

I also tried right-clicking a sprite to select it, then changing the Y value manually in the Translate panel.  But then it immediately selects whatever I had selected previously, and visually the Z-order does not change.

Is there a simpler way?
Thanks,
G.A.

**Comment by GimmickyApps** [comment]
Sorry, now I see "Z-depth".  Whoops.  Never mind!

**Comment by ndee85** [comment]
:-) No problem. Yes.. I called it z, since this is commonly used for depth ordering. Even though blenders depth axis is the y axis.

**Comment by GimmickyApps** [comment]
Just one other note for folks doing manual sprite layout in Blender: import your sprites in parenting order (torso first, etc.)--not all at once--otherwise when you go to do IK, things will not work very well.
