### ISSUE TITLE
Error finishing edit mesh

### ISSUE THREAD

**Issue by felixmunoz** [ndee85/coa_tools#120]
When I click on Finish Edit Mesh I receive this error:
![erro_bidu](https://user-images.githubusercontent.com/1693674/54475953-5835b900-47d6-11e9-9eb6-a0a11f8e250b.png)

**Comment by ndee85** [comment]
Hi Felix,
could you provide a testfile which I can look into? That way it is easier to fix.

**Comment by felixmunoz** [comment]
Hi, thanks for response. I think the problem is because I can't delete the rectangle vertices from mesh after edit. I send you a short video with the problem, a .blend file and the .json and .pngs.

My Blender version is 2.78

Please tell me if you need more information

Regards

[coa_error.zip](https://github.com/ndee85/coa_tools/files/2974471/coa_error.zip)

**Comment by felixmunoz** [comment]
Hi. I discover if I press TAB instead of click on Finish Mesh, the problem does not occur.
