### ISSUE TITLE
Mesh Creation issues

### ISSUE THREAD

**Issue by artbytarun** [ndee85/coa_tools#122]
I m trying to create a 2d character rig through the COA tools. It is not meant for gaming but something like Peppa Pig on blender.
I wanted to create a proper geometry instead of eyeballing the vertices because the mesh will deform properly if the geometry is laid out correctly instead of plotting them randomly. I used blender's modelling tools to create geometry for this purpose.
![before](https://user-images.githubusercontent.com/52741906/60964390-d2afb900-a330-11e9-914d-2a823d092083.PNG)

When I reopen my file the geometry gets distorted. Do I need to use only the COA tools Edit mesh option to create a mesh around the image and not Blenders default modelling tools? I had re-imported this image to test out the re-import feature. Is there a documentation about the do's and dont's I can read? Thank you
![after](https://user-images.githubusercontent.com/52741906/60964428-eb1fd380-a330-11e9-94ec-823d280989a7.PNG)

**Comment by anotherREYY** [comment]
I don't know about coding or something , but it seems that CoaTools have their own unique "properties" on its edit modes and general operators . 

So maybe we must use the CoaTools options to make everything works properly .

**Comment by artbytarun** [comment]
Thank you. That worked. I wanted to plot the vertices with precision so I edited them after I created the mesh with the COA tools.
