### ISSUE TITLE
How to setup different images in a Slot

### ISSUE THREAD

**Issue by artbytarun** [ndee85/coa_tools#124]
I had two questions. It would be great if some one could answer these. 'm new to Blender.

1. I want to swap images for different mouth shapes. I believe I need to do it with the slot feature. Could some explain the steps from Photoshop to setting it up in Blender. I could not get enough resources to figure it out.
2. Is the draw order animatable like Spine?
 
Thanks :)

**Comment by alcalyn** [comment]
This issue helped me: https://github.com/ndee85/coa_tools/issues/73

When I have multiple image I want to swap, I can create a slot in blender by selecting all images, and merging them to a slot.

Then in javascript, using dragonbones and pixi.js, I can do:

``` js
// Display eyes open
armature.armature.getSlot('eyes').displayIndex = 0;

// Display eyes closed
armature.armature.getSlot('eyes').displayIndex = 1;
```

**Comment by artbytarun** [comment]
I found a solution. I merged them into a slot. When you lick on the slot name in the COA outliner the slot index option shows up in the Sprite properties. It an be animated using the same Slot Index option.
