### ISSUE TITLE
Unable to use normal or triangle fill, only generate mesh

### ISSUE THREAD

**Issue by LunarBitz** [ndee85/coa_tools#126]
Using normal fill or triangle fill throws an attribute error
![error](https://user-images.githubusercontent.com/15371249/61574729-38b2e380-aa89-11e9-952d-ea13df50fcc9.png)

Blender Version: 2.8 Candidate release

**Comment by ndee85** [comment]
Triangle Fill is currently not available. This needs to be ported properly. Not yet done.
