### ISSUE TITLE
COA tools 2.8 fails with syntax errors when selected after load in Blender 2.8 (downloaded 2/8/2019)

### ISSUE THREAD

**Issue by kitheart** [ndee85/coa_tools#128]
as per title....
Previously loaded the older version of the coa tools before downloading the 2.8 version?
new/current coa version 2.0.0

**Comment by ndee85** [comment]
Hi kitheart,
please download latest version and retry. Should hopefully work now. It was a permission issue with copying icon files. Need to properly solve this. But no error anymore.
