### ISSUE TITLE
Edit armature offset from cursor

### ISSUE THREAD

**Issue by GimmickyApps** [ndee85/coa_tools#13]
Hi,
I'm a Blender noob, so maybe this isn't coa-specific, but somehow after just starting out with the armature, I went finish, made a sprite invisible, then went to edit again, and from that time on, the aimer follows the cursor but with an offset:

![armatureoffset](https://cloud.githubusercontent.com/assets/16719964/14059790/97efdc36-f34e-11e5-9d75-71871b58567d.gif)

How can I get it reset to normal?  Is this a bug or a Blender gaffe?

Thanks,
Gimmicky

**Comment by ndee85** [comment]
Hmm.. it seems it has to do with the camera. Leave the camera and everything should work ok.

**Comment by GimmickyApps** [comment]
Perfect, that did it!  Thanks!  (Press Numpad 0)
