### ISSUE TITLE
Few issues in Blender 2.8

### ISSUE THREAD

**Issue by Kuchtin** [ndee85/coa_tools#131]
Hello,

I used to do some animations in COA tools back in 2.79 Blender so I wanted to try the 2.8 version but I stumbled upon few issues. 

First one is more of a question: is there a way to make a triangle mesh fill? I couldn't find the option anywhere.

Another thing i stumbled upon while editing mesh is, that when I turn off the Snap vertices option, I get an 'coa.tools.draw_polygon' not found for space 'VIEW_3D' error. 

The last issue is related to posing. When i tried the pose my character, some sprites started disappearing and appearing again randomly. Then i found out that while in pose mode, even if I have 2D view turned on, the bones move in all 3 dimensions. 
![editmode](https://user-images.githubusercontent.com/36167727/63335900-7af86a80-c33e-11e9-8e49-f3ff3109552d.PNG)
![posemode](https://user-images.githubusercontent.com/36167727/63335901-7af86a80-c33e-11e9-8b43-b284b5b07634.PNG)

EDIT: I found out that this happens if you have the "SNAP DURING TRANSFORM" option in Blender enabled. turning it off makes transforms purely in 2D space.

Thank you for your answers

**Comment by alcalyn** [comment]
Have you tried to convert your file from 2.79 to 2.80 ?

I needed to do this to fixes some issues I had. To do this:

- Open search menu (in my case I press space)
- Search "coa", then select "Convert COA data(2.79 to 2.80)"

> is there a way to make a triangle mesh fill? I couldn't find the option anywhere.

I have also the same question, it looks like the button disappeared in COA tools 2.0.0 (but I still see in in source code).

**Comment by Kuchtin** [comment]
Oh, this is completely new project I made from scratch in 2.8.

**Comment by ndee85** [comment]
Hi,
triangle mesh is currently not available. At the moment it the workflow is meant to draw guide lines and then just use the generate mesh operator. More like so:
https://twitter.com/ndee85/status/943193083881062401
Though, the operator might come back :-)

The flickering of meshes is caused by blenders alpha blend mode. There is a new operator at the bottom where you can change the alpha mode of all sprites at once. Set it to hashed alpha, and the issue should be gone.

Please make sure to update to latest Blender28 branch. Since there have been quite a few updates and fixes in the past weeks.

**Comment by AnimaSomnia** [comment]
I'm using blender 2.83 and I get the 'coa.tools.draw_polygon' not found for space 'VIEW_3D' error whether I enable or disable the 'snap during transform' option.

The thing is though, I don't get this message with the first .png image I create a mesh for. After I successfully create one mesh, I get the error message when I try to place the first vertex point for the second .png image when creating the mesh. I've tried this multiple times and it's weird that I can always make the first mesh with no problems but can't make more than one mesh as I would get this error message regardless if the 'snap during transform' option is disabled or not.

Please help.
