### ISSUE TITLE
errors on installation on mac

### ISSUE THREAD

**Issue by Boo-zi** [ndee85/coa_tools#133]
hello. i installed coa tools on blender 2.8 on mac os, and at first all went well. the plugin was visible on the side menu (n) and it appears to be working (didn't check fully).

after changing layout and again, after restart blender checking all layouts, coa tools disappeared completely from the menu and it won't show again even thou it installed and showing on the add ons list.

also, in the 2d layout it doesn't showing at all.

thanks.

**Comment by ndee85** [comment]
Hi Boo-zi,
please try the latest Blender28 branch and see if it still happens. If so, make sure the addon is activated from the addons settings. If it is still not showing up, please provide a screenshot of the console output.

That will help me to debug the problem.

**Comment by Boo-zi** [comment]
Hi Andreas.
in the latest Stable blender built, the plugin working fine now.

thank you for your awesome work.

**Comment by ndee85** [comment]
Glad to hear. Closing the issue then.

Slowly the 2.8 branch is shaping up :-)
