### ISSUE TITLE
Weight paint doesn't stay on bones

### ISSUE THREAD

**Issue by faridosc** [ndee85/coa_tools#137]
If you add or remove weights from a bone and then you select another and do the same, if you go back to selecting the prior one the weights get removed.

Please help.

![COATOOLS_ERROR](https://user-images.githubusercontent.com/373726/64069726-09fe6000-cc26-11e9-8c12-dda6f5a8c39c.gif)

**Comment by ndee85** [comment]
Make sure you have Auto Normalize disabled. Auto Normalize will make sure that weights are attached to at least one bone. It's the checkbox below the brush settings.

**Comment by faridosc** [comment]
Will test right away. Thanks.

**Comment by ndee85** [comment]
Let me know if everything works. If so, feel free to close the issue :-)

**Comment by faridosc** [comment]
That does it. Thanks :D
