### ISSUE TITLE
Bone-binding workflow

### ISSUE THREAD

**Issue by GimmickyApps** [ndee85/coa_tools#14]
I'm probably again doing something wrong, but I tried to follow the video at https://www.youtube.com/watch?v=uoQZV1f_J1s and I'm not getting the same result.

From what I understood, I should go: edit armature, then right-click a bone, then tap (or hold, didn't seem to make a difference) Alt.  Red boxes appear around sprites, and I click the one I want to bind to.  I go finish armature, tap R, and rotate the sprite...but for me it pivots on the sprite's 0,0 and the bone doesn't move with it.

**Comment by ndee85** [comment]
You shouldn't rotate the sprite, but the bone. Select the Armature and go into pose mode. Then rotate the bone and the sprite should move with it.

**Comment by GimmickyApps** [comment]
Ah, super.  Thanks!  (So, Ctrl+Tab to go into pose mode.)  Works great!
