### ISSUE TITLE
Adding a file of the same name to a new sprite overwrites the old sprite's graphic too

### ISSUE THREAD

**Issue by GimmickyApps** [ndee85/coa_tools#16]
I had put all my graphics for each character into a folder with that character's name.  Now I have one character fully done and want to add the second one to the scene.

So I "Create new Sprite Object", then "Import Sprites" and import the second character's torso.png.  It appears correctly, but suddenly, the torso.png from the first character is now a scaled version of the second character's torso.

This is on Blender 2.77 with coa_tools up to date (Mar 22), on Win7x64.

**Comment by ndee85** [comment]
This is fixed with this commit 774c825
