### ISSUE TITLE
Unable to bind sprite to bone

### ISSUE THREAD

**Issue by FlynnD273** [ndee85/coa_tools#175]
How do I bind a sprite to a specific bone? In the demo, he just says "click out" I'm not sure how to do that? I click on the sprite itself, but nothing changes. Any help, please?

**Comment by davord45** [comment]
I had that problem on some Blender versions.I got it working on Blender 2.82 like in the demo

**Comment by FlynnD273** [comment]
> I had that problem on some Blender versions.I got it working on Blender 2.82 like in the demo

I can just click on the sprite after selecting a bone? Is that how it works?

**Comment by davord45** [comment]
Ok maybe you are looking at older tutorial.You bind bone to sprite in Edit Armature mode,select a bone and in N menu for COA tools next to sprite name there is a bone icon,thats for binding.Hope that fixes ur problem.

**Comment by FlynnD273** [comment]
Thank you! That works perfectly

**Comment by davord45** [comment]
Btw you can bind multiple bones to one sprite mesh.Making for some fast auto meshing.
