### ISSUE TITLE
Blender 2.92 COA doest appear in the n-panel 

### ISSUE THREAD

**Issue by cthnvisual** [ndee85/coa_tools#184]
Hi I am trying to use COA in blender 2.92, but it does not appear in the N-panel.

**Comment by jwhang627** [comment]
Similar problem here.

**Comment by hogragon** [comment]
Yeah, me too

**Comment by jwhang627** [comment]
Actually, I installed blender from flatpak instead of directly from repo. I installed COA there and it works.

**Comment by ndee85** [comment]
Please make sure to use the blender28 branch. The master is still for blender 2.79.
