### ISSUE TITLE
This version works on Blender 3 (̶m̶o̶s̶t̶l̶y̶)̶, with Cycles X, AAAAAAAAAAAA! (I use Linux)

### ISSUE THREAD

**Issue by Covamonas** [ndee85/coa_tools#190]
To my astonishment and surprise this version (filename: coa_tools-blender28.zip)works (̶m̶o̶s̶t̶l̶y̶)̶ on Blender 3, with Cycles X, AAAAAAAAAAAA! I use Linux and have been struggling and looking for work-arounds to install the add-on since forever. This just installed and worked on the Alpha Blender 3, w̶i̶t̶h̶ ̶s̶o̶m̶e̶ ̶n̶o̶n̶ ̶d̶e̶a̶l̶-̶b̶r̶e̶a̶k̶i̶n̶g̶ ̶g̶l̶i̶t̶c̶h̶e̶s̶.̶

**Comment by ndee85** [comment]
Hi Covamonas,
what are the non deal-breaking glitches?

**Comment by Covamonas** [comment]
Hey! Andreas! This is a great piece of software and has become an essential part of my workflow.

From Blender 2.9 I was not able to install the addon but in the Flatpak package and no other (don't know why), and there I could easily assign bones to sprites by selecting the bone and clicking the bone icon beside the sprite list in the N coatools window (I am not sure, I might have been using a different branch). Now in Blender 3, everything works (I can import the sprites, I can edit the armature, etc) but I don't see the bone icons anymore, I have to assign by alt + click on sprite, and this way is very wonky, it chooses a random sprite, not the one I'm clicking, so I have to hide every other sprite and show one by one the one I want to assign.

I tried installing other branches but it won´t activate and I get an error related to addon_update_ops; commenting the update lines I manage to activate it but I get an error when I try to edit the armature.

I hope this wonderful addon in not entirely abandoned.

Thank you. All the best

Ari

**Comment by Covamonas** [comment]
Hi Andreas, 

I can see the bones now, I have not idea why I couldn't before, but everything works fine now. Yeeeey!

![Screenshot_20211123_170700](https://user-images.githubusercontent.com/75699174/143143265-b38c579b-70a1-429e-b4c1-d53f77fdbfb4.jpeg)

**Comment by ndee85** [comment]
Ok, glad to hear. I will have a look at Blender 3.0 at some point and see if there need to be compatability fixes to be done.

**Comment by Covamonas** [comment]
That would be awesome!

**Comment by jwhang627** [comment]
Blender 3.0.0 is out and it only accepts with 1.0.4 version, but COA tool tab isn't showing.

**Comment by gameyakuza** [comment]
Doesn't work at all on my end, either this version or the one that was tweaked for 2.9.

**Comment by Covamonas** [comment]
I am on Linux using the 2.8 branch from https://github.com/ndee85/coa_tools/tree/blender28 with Blender 3.1 Alpha from https://builder.blender.org/download/daily/blender-3.1.0-alpha+master.5ef5a9fc2466-linux.x86_64-release.tar.xz which has resulted very stable for me, but be aware that saving your files on it will make them unusable for previous versions of Blender.

**Comment by BluePrintRandom** [comment]
there was a recent commit about custom bone shapes by hoogly boogly,
maybe this fixed this?
