### ISSUE TITLE
Remember output path for each animation

### ISSUE THREAD

**Issue by IBwWG** [ndee85/coa_tools#22]
Just a feature suggestion to make it easier to re-render :)

**Comment by IBwWG** [comment]
You know what would fix this, and also fix the fact that you can't have more than one camera resolution at a time?  (Setting the camera resolution seems to set it on ALL cameras.)  Support multiple scenes--each scene keeps track of its own output path automatically, and its own camera res.

I found only "Link Objects" for copying a scene seems to work with CoaTools--the others do not keep the animation keyframes of any of the animation collections.

To support scenes I think it would be sufficient to simply remember the current animation for all bone roots / characters and tie that to a scene.  Then it would work flawlessly.

**Comment by ndee85** [comment]
Added with this commit 0381edc4b3f204b7354e61d80544770666dec66f
So if Animation mode is set to "Action" the ouput name will be set to the selected Animation Collection name.
