### ISSUE TITLE
Draw Bone Shape

### ISSUE THREAD

**Issue by Mialie** [ndee85/coa_tools#23]
Hello Andreas, 

first of all, THANK YOU for the amazing Add On!! I was waiting for something, what could speed up my workflow, very very long time. I love Blender, it has so many possibilities and 2D animation is fun to do there too! 

I am learning how the futures are working, and I found during creating new bone shape, this issue, when I select bone in pose mode and then press "draw bone shape/create bone shape/new shape/ok":

![coa - report issue - draw bone shape](https://cloud.githubusercontent.com/assets/18292405/14292918/7af0e37c-fb6a-11e5-80ea-7806e5b2c15c.png)

I am not a programmer, so I unfortunatelly do not understand, where could be the problem...if you find some free time, could you please have a look? 

Thank you very much and just the best for you :)

**Comment by ndee85** [comment]
Hi @Mialie,
thanks.
Please make sure you are using the latest version of github. And then try to recreate the bug and tell me what steps you need to get to the bug.
Could be it is fixed in the latest version.

**Comment by Mialie** [comment]
Thank you for the answer!
I downloaded the zip file again, but it didn´t work.
But, I installed the newest verstion of Blender (2,77a) and there it is working!
I imported also my old user preferences and start up settings, and it still works. So I don´t know, where was problem, but it works now :)))) happy blending :)

**Comment by ndee85** [comment]
ok. good to know. :+1:
