### ISSUE TITLE
Issues with multiple frames

### ISSUE THREAD

**Issue by Draconis0868** [ndee85/coa_tools#25]
![birdwtf2](https://cloud.githubusercontent.com/assets/2031489/14476497/d6bc4c44-00bc-11e6-88fc-3650f364e7d4.gif)

Hi, first of all, let me thank you for making this great set of plugins. Our team has recently decided to jump to Godot to make our game and I've been hoping there would be a puppet2d/spline style tool to help animate the graphics for it so I was excited to see you were making the exact tool I was looking for, even better with mesh deform, and even better in blender.

Now with the issue: I've been having some recent trouble acclimating myself with it, I've figured out how to export from photoshop, to blender, to Godot and have had some success but I seem to be having more problems which I'll be happy to scratch up to me being new to this platform.

As you can see from the gif, I want to have the bird flap its wings and created a folder with --sprites that hold them. The first few frames work, but then the next ones seem to not pay any attention to the spritesheet.

I've also been having issues importing bones and animation into godot recently as well. (though not with this file) I've uploaded everything in hopes it can help figure out what's happening. The blender file has all the sprites embedded.

Thanks again for creating a much needed tool, I will donate when I am able, I'm very grateful for the the tools and I know it's going to make a huge difference in our game. (@paroxysmgame on twitter btw)

https://app.box.com/s/5cvor1ln4iokzq2l0008mxg86xlccn25

**Comment by Draconis0868** [comment]
Here is the first version I created, it has bones and the wing flaps were not put into a folder, but for some reason I can't animate the sprite being disabled/enabled. Also bones do not import into godot when exporting the json file.

https://app.box.com/s/ylgq0suge492g4yb59zkiafmsza0wppt

**Comment by ndee85** [comment]
hi @Draconis0868,
looking at the first blendfile you provided the tiling is set wrong. You should have 4 y tiles then the frames work perfectly fine.
One thing I also want to make clear. Currently mesh deformation only works in blender. Godot has no support for that right now. So you can only use normal sprites attached to bones. So no smooth deformations. Another limitation is non uniform bone scaling. Godots bone system is not a real bone system. It is just a way to draw nodes and give a better distinction for them. The bones are not working in its own space which can result in weird scaling when using non uniform scaling. So the exporter makes all scaling uniform when exporting.

I will take a look at the second file and see if I can get it running in godot with animations. I'll wirte again.

**Comment by ndee85** [comment]
ok.. just noticed that my ps exporter seems to not properly export the tile size. I will take a look at it. As said, just change the value manually for now.

**Comment by ndee85** [comment]
ok. phtoshop exporter is fixed. Exporting should work fine now and the tilesize should be set properly.
Looking at exporting to godot next.

**Comment by ndee85** [comment]
As said above. Mesh deformation does not work in godot yet. Thus they way you set up the bird will not work. Unfortunately. :(
I would love if godot has support for mesh deformation. Maybe a different solution for you could be the animation suite [creature](http://creature.kestrelmoon.com/). I know its commercial, but it seems the dev just added godot support via godots module system.
Check it out here: https://www.youtube.com/watch?v=jkjWR21lAqY

**Comment by Draconis0868** [comment]
Ah ok, well, there's always the multiple pieces approach for the neck and other parts, not a big deal, I was doing that at first with unitys basic engine before I got puppet2D. Thanks for the information. Creature is fantastic but a little too expensive for me right now, so I will stick with your COATools.  Hopefully Mesh Deformation will be supported later. Thank you very much!

**Comment by ndee85** [comment]
Good to hear you are sticking to coa tools.
I have made a few fixes to the json exporter based on your delivered file. Was a great resource to fix a few issues. It is really a pitty mesh deformations do not work in godot. I have to talk to @reduz, he wanted to add such features in the future :)

New commit will come soon.

**Comment by Draconis0868** [comment]
Awesome! Happy it helped!

**Comment by ndee85** [comment]
ok.. I'll close this issue for now. I made some improvements for the exporter based on that file. Unfortunately mesh deformations do not export for now.
Changes arrived with this commit af0630a
