### ISSUE TITLE
Spriter support

### ISSUE THREAD

**Issue by IPv6** [ndee85/coa_tools#30]
Is this possible to export animation into spriter data format?
Spriter runtime working on many platforms (includin flash for example), so your cool tool will not be limited to GODOT

**Comment by ndee85** [comment]
Probably not going to happen from my side. 
But I have now implemented an open format. The Dragonbones json export format is now fully supported in coa tools. That way you have also access to many other engines. 
More info on dragonbones can be found here:
http://dragonbones.com/en/index.html

**Comment by blurymind** [comment]
Spriter is nice, but it's devs have been rewriting the file specification and runtimes from scratch for spriter 2, so even if you write some export capabilities - you may have to rewrite them in a few months again.

Apart of that spriter also does not support mesh deformation and is proprietary.
It's runtime licenses dont seem to lock the user to their editor, but the runtimes are limited at the moment.
