### ISSUE TITLE
Unable to rotate view while plugin is enabled

### ISSUE THREAD

**Issue by boringuser** [ndee85/coa_tools#33]
I suspect this is intentional behavior, but when COA Tools is enabled and I rotate the view, as soon as I press any key the view snaps back to front. There are times when I want to make manual adjustments to the scene and this isn't always possible if COA Tools is enabled (particularly if I want to move something along the Y axis). Can this behavior be disabled or put behind a configuration setting so it can be turned off? Thanks!

**Comment by ndee85** [comment]
@boringuser 
In the Cutout Animation Tab you have a 3D View and 2D View button. Just use the 3D and everything should work fine.

**Comment by ndee85** [comment]
Small note, this 2D/3D View works per Screen. So each screen can have its own setting.
