### ISSUE TITLE
Double click to rename collection instead leaks 200 MB of memory and does nothing

### ISSUE THREAD

**Issue by IBwWG** [ndee85/coa_tools#35]
I'm not sure with what version of coa_tools I could rename still, but with [the latest](https://github.com/ndee85/coa_tools/commit/eab992621bc434532d5c253e495bb523f1ec9e17) on blender 2.77a, whenever I've tried double-clicking to rename a collection, like the mouseover tooltip says, instead of allowing a rename, my laptop's fans spool up for a couple seconds, blender claims an additional 200 MB of RAM, and nothing else happens.  I tried it four times over the last minute, and blender is now sitting on 1.6 GB and will need a restart to continue working much longer (at least, this is how it seems to be on my system.  I only have 4 GB to begin with.)

200 MB is also the amount it takes adding a new collection.

**Comment by ndee85** [comment]
Hmm.. renaming is strange in general. I'll have a look.

**Comment by ndee85** [comment]
I cannot reproduce this on my side, but I have found another bug when keying multiple sprites at once. This could result in not proper action naming. This is fixed now. I don't know if this may be connected.
If it still does not work, please provide a blend file where this happens so I can take a look at it.

**Comment by IBwWG** [comment]
With the latest code, renaming works now, sometimes.  It just let me rename 2 entries, but then after that would not let me rename any more.  Meanwhile each attempt still leaks 200 MB.

**Comment by ndee85** [comment]
This is strange... does it also happen for a newly setup file? If not, could you provide a blend?

**Comment by IBwWG** [comment]
I think I actually need to triple-click before anything happens.  That seems to be consistently it.  Double-clicking just leaks memory.  I'll try on a fresh file.

**Comment by IBwWG** [comment]
On a fresh file, double-clicking works fine to rename, although still leaks a few 100 KB, but only after the rename.  Maybe it's a lag issue.

**Comment by IBwWG** [comment]
Here it is:

1. fresh file
2. import my four sprite sheet files (totaling 4 MB)
3. create new collection with + icon
4. double click NewCollection

Every time you do that fourth step, it doesn't let you rename, and leaks 35 MB.

**Comment by IBwWG** [comment]
OK given my comment in the other thread I'm going to close this, because it seems clear from the numbers that, once there's actually data to work with, the lag causes a double click to register as two single clicks, leaking twice the amount of memory.  So this is actually just a side-effect of #37.

**Comment by ndee85** [comment]
yep. Lets discuss the rest in #37
