### ISSUE TITLE
Frame index preview only shows first frame until clicking on first frame

### ISSUE THREAD

**Issue by IBwWG** [ndee85/coa_tools#36]
This is again on [this version](https://github.com/ndee85/coa_tools/commit/eab992621bc434532d5c253e495bb523f1ec9e17) with blender 2.77a but I'm not sure when it changed.  The preview takes a few seconds to generate (even with a small number of frames) and then only shows the first frame, even when I'm currently on a different frame index.

**Comment by IBwWG** [comment]
Oh, never mind, you have to click the single-frame preview to get all the frames.  Didn't it used to be that clicking the small icon to the left of the keyframe icon would give you the preview with one click?

**Comment by ndee85** [comment]
nope. It was always with 2 clicks. The problem is, I cannot make this enum property so small as I like to work with one click. Thats the reason why I have made this small button operator which actually opens the enum prop from where you then can select.

**Comment by IBwWG** [comment]
Ah, OK, sorry for my bad memory :)

**Comment by ndee85** [comment]
no problem ^^
