### ISSUE TITLE
Switching collections leaks memory

### ISSUE THREAD

**Issue by IBwWG** [ndee85/coa_tools#37]
On or before https://github.com/ndee85/coa_tools/commit/eab992621bc434532d5c253e495bb523f1ec9e17 with blender 2.77a win7sp1x64.

These are single clicks, although maybe related to #35?

![ct-mem-leak](https://cloud.githubusercontent.com/assets/16719964/18077856/9024b7e6-6e88-11e6-89c4-2acf53e711a1.gif)

**Comment by IBwWG** [comment]
(It's possible this was an old bug.  I've always had to restart blender once in a while--I've only been using blender with coa_tools--because of memory leaks, but I hadn't realized when exactly they were occurring.  This seems to be one of the bigger ones.)

**Comment by ndee85** [comment]
Ok.. I'll have found a bug when adding keyframes for multiple sprites at once resulting in not proper action naming. I don't know if this may be the case or not. Please try out latest version, just pushed something.
If this doesn't help, please provide a test blend where the problem occurs. I cannot reproduce it on my side.

**Comment by IBwWG** [comment]
OK thanks!

**Comment by IBwWG** [comment]
Nope, still leaking here.  Note this one is not about naming, just about switching, with a single click.

**Comment by IBwWG** [comment]
Can I e-mail you my project?

**Comment by ndee85** [comment]
yes.. Email to andreasesau [at] gmail.com

**Comment by IBwWG** [comment]
Here, I can even just e-mail you the test with the sprites that I made for #35.

It's interesting to note, in this test one, a single click to switch collections leaks 17 MB, and a double-click to try to rename seems to register as two single clicks, because then it leaks twice as much.

**Comment by IBwWG** [comment]
Or maybe you're able to reproduce it with such a simple repro case?  I can't imagine that it has anything to do with my specific 4 MB of sprite sheets.  :)

**Comment by ndee85** [comment]
what about renaming with ctrl+click on the name? Double click will also set the index of the anim collection. This will reassign all actions, this may cause the lag?! For me I cannot notice any memory leaks.

**Comment by IBwWG** [comment]
Ctrl+click works great!  Thanks, that's a super workaround.  (I'm a blender n00b still, and apparently will be for a while, there are so many shortcuts and things to learn.)  But that only fixes the rename and not the switching leak.  So you put in 4 MB of sprites and don't have a 17 MB leak on switch?  OK then I will e-mail my sprite sheets to you...

**Comment by ndee85** [comment]
So it seems it has nothing to do with renaming, but rather with switching/assigning actions. Then I'll close the rename issue and we keep this open for further discussion.

**Comment by IBwWG** [comment]
Already done :)

**Comment by IBwWG** [comment]
Maybe it's an OS difference, are you on Linux?

**Comment by ndee85** [comment]
ok.. I took a look at it.. I have to say, I don't know if this is even a bug, or usual blender behavior. When adding a few textures to a texture slot, and selecting the textures results also in increasing the usage of memory space. I don't think I can do something there...

**Comment by IBwWG** [comment]
So...selecting textures multiple times should eventually run out of memory?  If it's usual blender behaviour, I'd say it's a blender bug, then...

**Comment by IBwWG** [comment]
Like clicking back and forth between two collections continually leaks memory on every click.  It's not like after you've selected each collection once, it stops leaking for selecting that particular collection.  In the case of my (not overly complicated) project, this means I get < 10 switches max before blender has used up all the memory it can on my system, and grinds to a halt.

**Comment by IBwWG** [comment]
Anyway many thanks for taking a look.

**Comment by ndee85** [comment]
I would say blender will free the memory from time to time... Maybe this is done that way for proper undo behavior and maybe other internal functionality.

**Comment by IBwWG** [comment]
Guess I just need a better system then :(  oh well, maybe some day...
