### ISSUE TITLE
Frame range start overridden to 0?

### ISSUE THREAD

**Issue by IBwWG** [ndee85/coa_tools#39]
I'm not sure if this is intentional or not, but with CoaTools disabled, it doesn't happen, so I guess it must be caused by CoaTools: http://blender.stackexchange.com/questions/62134/why-does-my-frame-range-start-automatically-revert-back-to-0-after-i-set-it/62169#62169

![b3d-startframe-cannot-set](https://cloud.githubusercontent.com/assets/16719964/18192934/ee7093d6-70d8-11e6-95e9-d8c4fd655510.gif)

If it is intentional, could there be a way to disable it without having to disable the plugin entirely?  (For the record, I tried changing CoaTools' own "Frame Start" in the collections pane, but it doesn't seem to have any effect anywhere that I can see.)

**Comment by ndee85** [comment]
@IBwWG sorry for the late response. I'll fix this as soon as I get time. This is indeed done by my addon. Usually when you don't have any anim collections it won't set the framerange. And when selecting NO ACTION it actually shouldn't set the frame range. Going to fix it.

**Comment by IBwWG** [comment]
No worries at all, it's certainly easy enough to work around this, just delete the frames you don't need afterwards.  Also my animating is now done so no rush on my end anyway.  But many thanks for responding :)  Cheers.

**Comment by ndee85** [comment]
This is fixed now. The Frame Range now gets only set if you select an Animation Collection. Otherwise it stays as it is.
