### ISSUE TITLE
Armature - Weight Paint Issues

### ISSUE THREAD

**Issue by southernshotty** [ndee85/coa_tools#40]
Hey wondering if you have any solutions to these issues I'm having?

-Whenever I try to draw the bones, it doesn't draw at my cursor. It draws several units offset.
-Whenever I try to weight paint - it'll only paint everything read, I can't subtract.
-When I edit mesh and draw/triangulate my own. The original border disappears and won't let me delete the old border.

What version and OS are you using?

**Comment by ndee85** [comment]
You have a Property on the left that is called "Hide Base Sprite" when a sprite is selected. This lets you hide the base sprite and then only your custom mesh is displayed. You can show it at any time if you need it. 

Are you in camera mode when you try to draw bones. It seems when you are in camera mode there is a matrix missing that needs to be multiplied to get proper coords. Just leave the camera and set the view to 2D. Then it should work fine. 

About weight painting. You can disable the auto normalize and subtracting should work fine.﻿

**Comment by ndee85** [comment]
Ok.. I think this issues were resolved. So closing it.
