### ISSUE TITLE
If folder with --sprites has only one sprite/folder in it. It creats sheet with one empty sprite.

### ISSUE THREAD

**Issue by n-pigeon** [ndee85/coa_tools#44]
If I make folder with --sprite which contains only one sprite/folder and export it. Resulting spritesheet contains my sprite and second empty sprite.

**Comment by ndee85** [comment]
Ok, I'll take a look at it

**Comment by ndee85** [comment]
Ok.. this should be fixed. Please test and report if something unecpected happens.
bafb87ee5a5fdbfacae363c221cbf193818cc4b6
