### ISSUE TITLE
COA tools doesn't support user setting where selection is set to left mouse button instead right

### ISSUE THREAD

**Issue by n-pigeon** [ndee85/coa_tools#45]
Yes I'm one of those users :D

I intuitively tried to use Left Mouse Butten when I was drawing new bones and assigning sprites to bones and was curious why it doesn't want to work. They I discovered that it's reversed and I've should use Right Mouse Button when rest of the blender is set to LMB. ^^

**Comment by ndee85** [comment]
Well this is somewhat akward in blender. If you switch left right you also need to draw your bones with rightclick and alt + rightclick to pick objects in the armature mode. I needed to switch this to make it work properly. Unfortunatenly I don't see a workaround for that right now but use the inversed left right keys also draw drawing bones and picking sprites.
