### ISSUE TITLE
Sprite sheet frames keyframes should be set to constant interpolation.

### ISSUE THREAD

**Issue by n-pigeon** [ndee85/coa_tools#50]
By default they were set to linear which made frame of sprite switch between two keyframes instead on the second keyframe :)

All animateable integers properties should be auto constant. I have no idea why Blender doesn't do it by default... :B

**Comment by ndee85** [comment]
You can ctrl+click on the keyoperator. This will show you constant, linear and bezier interpolation.
Choose freely. But yes.. Probably constant makes more sense by default. Will change that.

**Comment by n-pigeon** [comment]
Oh cool didn't know that thx :)

**Comment by ndee85** [comment]
Ok.. I noticed there was a bug in my code. It was already set to constant by default, but didn't work in all cases properly. This is fixed now. And as already said. Ctrl+Click will let you choose.
