### ISSUE TITLE
Wrap Animation Playback starts from 0 frame not currently set start frame

### ISSUE THREAD

**Issue by n-pigeon** [ndee85/coa_tools#53]
After scrolling to end frame frame tracker jumps to frame 0 not to currently set start frame :)

**Comment by ndee85** [comment]
Hmm.. the Frame Start and Frame End only takes effect if set to NLA Mode. Otherwise it won't. Animation Collections always start from frame 0.

**Comment by ndee85** [comment]
But still.. it makes sense to let it jump to the first frame and not to 0 ^^ I will change that

**Comment by ndee85** [comment]
Fixed with this commit c2dacb2f070785ab3aa5778c58c0e79a459dccf6
