### ISSUE TITLE
binding sprites to bones seems to be broken

### ISSUE THREAD

**Issue by PostPollux** [ndee85/coa_tools#54]
Hello, I'm using the newest coa tools (downloaded today from github) with blender 2.78a.

Everything works fine until I'm at the point where I want to bind the sprites to the bones.
In "Edit Armature" mode I select a bone, then press "alt". Now hovering over the sprites work well, they get highlighted, you see the name... but when I now click on them nothing happens. 

Am I doing something wrong or is it just a bug?

**Comment by PostPollux** [comment]
Sorry for the unnecessary report. I found out, that I have to press "alt", hover the bodypart, then press shift and then click.
I didn't find any documentation, that's why I made a report here. And in your first Video "Dev1 Log" you didn't mention to press shift...
Anyway, thanks for this great tool!

**Comment by ndee85** [comment]
Hmmm.. this is stange. Usually shift is not needed. And I never use it. Do you have swapped left and right mouse, or do you use enable 3 mouse button?

**Comment by PostPollux** [comment]
No I'm using standard mouse settings in Blender. What is that 3 mouse button thing? And where do I enable or disable it?

I had a look in the code yesterday (edit_armature.py) and I think here at line 386 it decides whether to bind the sprites or not. But I can't find anything related to the shift key. So I have no clue where this comes from....
` ### mouse just pressed
                if not self.mouse_press_hist and self.mouse_press and self.in_view_3d and self.object_hover != None:`
