### ISSUE TITLE
grease pencil support/workflow

### ISSUE THREAD

**Issue by Quentie** [ndee85/coa_tools#57]
First of thanks for this awesome tool. Especially the upcoming dragonbones support is a really cool move.
Just saw this video of [grease pencil + bones](https://vimeo.com/173325517) in action and I'm curious if It would be possible to use the coa_tools exporter to get such an animation into your game engine of choice?

**Comment by blurymind** [comment]
Coa tools would need to be able tp convert grease pencil drawings into a
spritesheet somehow..

Not sure how complicated that would be

**Comment by ndee85** [comment]
Grease Pencil Support is not going to happen. COA tools is based on a bitmap approach. So grease pencil is a format thats not going to work.
As @blurymind said. There should be a way to somehow bake grease pencil into a spritesheet.

**Comment by Quentie** [comment]
@blurymind @ndee85 Yes this makes sense of course. Not sure if baking grease pencil into a spritesheet is really worth the afford.  Thanks
