### ISSUE TITLE
Sprites just disappeared

### ISSUE THREAD

**Issue by LPsyCongroo** [ndee85/coa_tools#59]
I'm quite at a loss about what happened.  I was weight painting when all of my sprites (save the one I was working on) just stopped showing up.  The files are still there in the hierarchy I just cant see them in 3d view anymore.  I've been trying to get it back for hours.  

![image](https://cloud.githubusercontent.com/assets/16440817/20863720/4b93ae74-b9a2-11e6-9d0b-545bbe2df68f.png)

I'm not the most experienced blender user so I'm not sure what's happening, or if it even has anything to do with COATools.  Any ideas?

I'm also getting this when I select a bone or try to export: 
![image](https://cloud.githubusercontent.com/assets/16440817/20863750/8c7b0512-b9a3-11e6-816f-faf7b1ea7814.png)

It's not letting me import new sprites either:
![image](https://cloud.githubusercontent.com/assets/16440817/20865966/61aee038-b9ee-11e6-9dbc-340caa7c89f8.png)

**Comment by ndee85** [comment]
Press the "/" sign on the numpad, this will end the local view. Once you are entering the Edit weights mode the addon starts a local view with that particular sprite.

**Comment by LPsyCongroo** [comment]
Thanks.  It took me some time to figure it out because I'm still a bit new to blender.  I forgot to close this earlier.
