### ISSUE TITLE
Edit mesh function with sprite sheet problem.

### ISSUE THREAD

**Issue by ja777on** [ndee85/coa_tools#7]
When you edit mesh with multiple sprite sheet and triangulate it... mesh shows whole sprite sheet texture on it ! After that frame index function disappear.

**Comment by ndee85** [comment]
Triangulated meshes do not work with sprite sheet textures together. If you want to use a spritesheet the mesh is only allowed to have 4 vertices.

**Comment by ja777on** [comment]
Is there way to have that option? Or to chose how much vertices we wont on mesh?
It would be quite nice for better distortion of texture. (3d effects head turns etc.)

**Comment by ndee85** [comment]
I have added this function some time ago now. So this should work fine now. Closing this issue.
