### ISSUE TITLE
Duplication problem with the mech

### ISSUE THREAD

**Issue by Nevimmu** [ndee85/coa_tools#70]
Hi
I tried to use create a mesh and worked great, but when I start to move it it look like I have a duplicate of that part and it's weird.
![capture d ecran 57](https://user-images.githubusercontent.com/26687441/27699734-8853556a-5cfb-11e7-8de6-c985e6094210.png)

And if I try to weight paint it's really weird too

![capture d ecran 57](https://user-images.githubusercontent.com/26687441/27699962-61e84182-5cfc-11e7-8b87-e116c5bec10d.png)

**Comment by ndee85** [comment]
@Nevimmu 
you should toggle the "Hide Base Sprite" checkbox. Then everything should look fine. Or you can go into Edit Mode and unhide all vertices and delete the unneeded face.

**Comment by Nevimmu** [comment]
Oh it work, thank you very much
