### ISSUE TITLE
bug while importing

### ISSUE THREAD

**Issue by z-uo** [ndee85/coa_tools#78]
![bug](https://user-images.githubusercontent.com/652668/35403383-ccd66eda-01ff-11e8-90fe-0d48649539c2.png)
Hello, this is what happen everytime I try to import a sprite (.png) into blender.
I just wanted to test this addon, so I've made the same step as in the introduction video.
I use blender 2.79 on windows 10.

**Comment by ndee85** [comment]
Sorry for that. I made some changes and it seems I introduced this bug. I will fix this as soon as possible.
I asume you are using latest Github Version? If so, you will automatically be notified once the fix is ready. You can update the addon from within blender with autonotification.

**Comment by ndee85** [comment]
This should be fixed. 
You can update by going into the addon preferences. Press the Check for Updates button and then install the latest version from master. Do not forget to restart blender.
![update](https://user-images.githubusercontent.com/6723918/35431081-686021b8-027b-11e8-8ee4-4442c95f6725.png)

**Comment by z-uo** [comment]
Thanks for your quick reply and fix, the import works fine but then I can't draw bones.
Then I see you made a 1.0 version just yesterday which I now use and works great :)
thanks
