### ISSUE TITLE
fake_module: addon missing 'bl_info' gives bad performance!

### ISSUE THREAD

**Issue by kuca2002** [ndee85/coa_tools#96]
it gives me this error in the console
`fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater_ops.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\developer_utils.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions_draw.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater_ops.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\developer_utils.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions_draw.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon_updater_ops.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\developer_utils.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\functions_draw.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui.py'
Modules Installed () from 'D:\\Download\\coa_tools-master\\Blender\\coa_tools\\__init__.py' into 'C:\\Users\\ruszev\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'`

**Comment by ndee85** [comment]
How did you install the addon?
Make sure to zip the the coa_tools directory which is located in the Blender directory. The zipped directory then can be installed via the addon manager.

**Comment by kuca2002** [comment]
great thanks that did the trick! Maybe you could include this into the installation guide or im just blind and didnt see it

**Comment by ndee85** [comment]
Its described on the start page ;-)
Good to hear everything works now. Closing this issue.
