### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by trigdog** [ndee85/coa_tools#97]
Are there plans on supporting Blender 2.8?

**Comment by Schroedingers-Cat** [comment]
You are specifically talking about the upcoming features to Blender's grease pencil, aren't you? https://www.youtube.com/watch?v=h3iyy-gGeIU  

This would be really cool. Currently, there is no software that allows you to paint, rig, animate and directly export to an engine like Unity. With coa tools supporting the upcoming Blender features, this would be possible via DragonBones export making Blender the only all-in-one-solution for 2D artists.

**Comment by mundusnine** [comment]
@Schroedingers-Cat  No need to export to unity, just use [Armory3D](https://armory3d.org/)

**Comment by morevnaproject** [comment]
Ongoing work here - https://github.com/ndee85/coa_tools/tree/blender28

**Comment by ndee85** [comment]
As already mentioned. Blender2.8 is addon is actively developed. So closing this one.
